# Generated by Django 4.2.6 on 2023-11-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_alerte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='etat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alerte',
            name='taux',
            field=models.FloatField(default=0),
        ),
    ]
