# Generated by Django 4.2.6 on 2023-11-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_alerte', '0002_alerte_etat_alerte_taux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capture',
            name='capture',
        ),
        migrations.AddField(
            model_name='capture',
            name='base64',
            field=models.TextField(default=''),
        ),
    ]
