# Generated by Django 4.2.6 on 2024-01-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_alerte', '0003_remove_capture_capture_capture_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
