# Generated by Django 4.2.6 on 2024-01-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_alerte', '0004_alter_capture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='url',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
