# Generated by Django 4.2.6 on 2024-02-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_alerte', '0005_alter_capture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='alerte',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
